{"name": "Successful login with valid credentials", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n\tGetHandleVerifier [0x00ECFC83+61635]\n\tGetHandleVerifier [0x00ECFCC4+61700]\n\t(No symbol) [0x00CF05D3]\n\t(No symbol) [0x00D3899E]\n\t(No symbol) [0x00D38D3B]\n\t(No symbol) [0x00D80E12]\n\t(No symbol) [0x00D5D2E4]\n\t(No symbol) [0x00D7E61B]\n\t(No symbol) [0x00D5D096]\n\t(No symbol) [0x00D2C840]\n\t(No symbol) [0x00D2D6A4]\n\tGetHandleVerifier [0x011545A3+2701795]\n\tGetHandleVerifier [0x0114FD26+2683238]\n\tGetHandleVerifier [0x0116AA6E+2793134]\n\tGetHandleVerifier [0x00EE6945+155013]\n\tGetHandleVerifier [0x00EED02D+181357]\n\tGetHandleVerifier [0x00ED74D8+92440]\n\tGetHandleVerifier [0x00ED7680+92864]\n\tGetHandleVerifier [0x00EC2070+5296]\n\t(No symbol) [0x76AD5D49]\n\tRtlInitializeExceptionChain [0x77E7CF0B+107]\n\tRtlGetAppContainerNamedObjectPath [0x77E7CE91+561]\n\n", "trace": "  File \"C:\\Users\\Digital Suppliers\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Digital Suppliers\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features\\steps\\login_step_parameters.py\", line 15, in step_impl\n    context.page.enter_credentials(username, password)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Automation\\PAT-EB-6\\Behave-Day2\\pages\\login_page.py\", line 13, in enter_credentials\n    self.wait.until(EC.visibility_of_element_located(Locators.username_field)).send_keys(username)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Digital Suppliers\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I am on the orangehrm login page", "status": "passed", "start": 1747549666587, "stop": 1747549737060}, {"name": "When I login with username \"Admin\" and password \"admin123\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n\tGetHandleVerifier [0x00ECFC83+61635]\n\tGetHandleVerifier [0x00ECFCC4+61700]\n\t(No symbol) [0x00CF05D3]\n\t(No symbol) [0x00D3899E]\n\t(No symbol) [0x00D38D3B]\n\t(No symbol) [0x00D80E12]\n\t(No symbol) [0x00D5D2E4]\n\t(No symbol) [0x00D7E61B]\n\t(No symbol) [0x00D5D096]\n\t(No symbol) [0x00D2C840]\n\t(No symbol) [0x00D2D6A4]\n\tGetHandleVerifier [0x011545A3+2701795]\n\tGetHandleVerifier [0x0114FD26+2683238]\n\tGetHandleVerifier [0x0116AA6E+2793134]\n\tGetHandleVerifier [0x00EE6945+155013]\n\tGetHandleVerifier [0x00EED02D+181357]\n\tGetHandleVerifier [0x00ED74D8+92440]\n\tGetHandleVerifier [0x00ED7680+92864]\n\tGetHandleVerifier [0x00EC2070+5296]\n\t(No symbol) [0x76AD5D49]\n\tRtlInitializeExceptionChain [0x77E7CF0B+107]\n\tRtlGetAppContainerNamedObjectPath [0x77E7CE91+561]\n\n", "trace": "  File \"C:\\Users\\Digital Suppliers\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Digital Suppliers\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features\\steps\\login_step_parameters.py\", line 15, in step_impl\n    context.page.enter_credentials(username, password)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Automation\\PAT-EB-6\\Behave-Day2\\pages\\login_page.py\", line 13, in enter_credentials\n    self.wait.until(EC.visibility_of_element_located(Locators.username_field)).send_keys(username)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Digital Suppliers\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1747549737060, "stop": 1747549747139}, {"name": "And I click the login button", "status": "skipped", "start": 1747549747144, "stop": 1747549747144}, {"name": "Then I should be redirected to the dashboard page", "status": "skipped", "start": 1747549747144, "stop": 1747549747144}], "start": 1747549666585, "stop": 1747549747144, "uuid": "670deea2-5f0e-441f-8c7a-fef9eecda5ae", "historyId": "e0d1f100f051188d0c30de87e6127e01", "fullName": "Login Functionality on OrangeHRM Website: Successful login with valid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "smoke"}, {"name": "tag", "value": "valid"}, {"name": "feature", "value": "Login Functionality on OrangeHRM Website"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}